###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: teste-pagarme-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=teste_pagarme
        - MYSQL_USER=pagarme
        - MYSQL_PASSWORD=123

    webserver:
      image: nginx:alpine
      container_name: teste-pagarme-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - php-fpm
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: teste-pagarme-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    data:
      image: busybox
      container_name: teste-pagarme-data
      working_dir: /application
      volumes:
        - ./application:/application
